service: echobot

provider:
  name: aws
  region: us-west-2
  runtime: java8
  timeout: 20
  environment:
    BOT_TOKEN: ${env:BOT_TOKEN}
    BOT_USER_ID: ${env:BOT_USER_ID}

functions:
  event_receive:
    handler: com.merricklabs.echobot.handlers.EchoBotHandler
    memorySize: 256
    events:
      - http:
          path: event/receive
          method: post
          # The following makes this endpoint async, so it immediately
          # returns 200 while the Lambda is still processing.
          # Otherwise Slack will retry messages which results in duplicate responses.
          async: true

package:
  artifact: build/libs/echobot-dev.jar