service: karmabot

custom:
  tableName: karmabot
  dynamoEndpoint: https://dynamodb.us-west-2.amazonaws.com

provider:
  name: aws
  region: us-west-2
  runtime: java8
  timeout: 20
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:*:*:table/${self:custom.tableName}

functions:
  event_receive:
    handler: com.merricklabs.karmabot.handlers.KarmaBotHandler
    memorySize: 256
    events:
      - http:
          path: event/receive
          method: post
          cors: ruet

package:
  artifact: build/libs/karmabot-dev.jar

resources:
  Resources:
    KarmaDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: karma_id
            AttributeType: S
        KeySchema:
          - AttributeName: karma_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}