service: echobot

provider:
  name: aws
  region: us-west-2
  runtime: java8
  timeout: 20
  environment:
    BOT_TOKEN: ${env:BOT_TOKEN}
    BOT_USER_ID: ${env:BOT_USER_ID}

functions:
  event_receive:
    handler: com.merricklabs.echobot.handlers.EchoBotHandler
    memorySize: 256
    events:
      - http:
          path: event/receive
          method: post
          cors: ruet

package:
  artifact: build/libs/echobot-dev.jar