service: karmabot

provider:
  name: aws
  region: us-west-2
  runtime: java8
  timeout: 10

functions:
  event_receive:
    handler: com.merricklabs.karmabot.handlers.KarmaBotHandler
    memorySize: 128
    events:
      - http:
          path: event/receive
          method: post
          cors: ruet

package:
  artifact: build/libs/karmabot-dev.jar
